kind: pipeline
type: docker
name: default

steps:
- name: package
  image: maven:3-jdk-8
  environment:
    TZ: Asia/Shanghai
  volumes:
  - name: maven-cache
    path: /root/.m2
  - name: build
    path: /app/build
  commands:
  - mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - cp -rf ruoyi-admin/target/ruoyi-admin.jar /app/build
- name: build
  image: node
  environment:
    TZ: Asia/Shanghai
  volumes:
  - name: npm-cache
    path: /drone/src/ruoyi-ui/node_modules
  - name: build
    path: /app/build
  commands:
  - cd ruoyi-ui/
  - npm install
  - npm run build:prod
  - rm -rf /app/build/dist
  - cp -rf dist /app/build/dist
volumes:
- name: build
  host:
    path: /home/ubuntu/build
- name: maven-cache
  host:
    path: /home/ubuntu/.m2
- name: npm-cache
  host:
    path: /home/ubuntu/cache/node_modules
